package tech_service

import (
	"github.com/anthophora/tamircity/pkg/models/db/tech_service"
	"time"
)

var Reservation1 = &tech_service.Reservation{
	ReservationDate:   time.Now(),
	StartOfHour:       13,
	EndOfHour:         14,
	Price:             100,
	Status:            tech_service.Pending,
	FullName:          "Kullanıcı 1",
	Email:             "msk@test.com",
	PhoneNumber:       "05555555555",
	SecondPhoneNumber: "05555555555",
	Description:       "Güzel hizmet",
	DeviceType:        DeviceTypePhone,
	Brand:             BrandApple,
	ModelEntity:       ModelIphone12,
	FixType:           FixType1,
	ServiceType:       ServiceType1,
	ExtraService:      ExtraServiceFirst,
	TechnicalService:  TechnicalService1,
}

var Reservation2 = &tech_service.Reservation{
	ReservationDate:   time.Now(),
	StartOfHour:       15,
	EndOfHour:         16,
	Price:             150,
	Status:            tech_service.Cancelled,
	FullName:          "Kullanıcı 2",
	Email:             "msk@test.com",
	PhoneNumber:       "05555555555",
	SecondPhoneNumber: "05555555555",
	Description:       "Güzel hizmet",
	DeviceType:        DeviceTypePhone,
	Brand:             BrandApple,
	ModelEntity:       ModelIphone12Pro,
	FixType:           FixType1,
	ServiceType:       ServiceType1,
	ExtraService:      ExtraServiceFirst,
	TechnicalService:  TechnicalService1,
}

var Reservation3 = &tech_service.Reservation{
	ReservationDate:   time.Now(),
	StartOfHour:       17,
	EndOfHour:         18,
	Price:             150,
	Status:            tech_service.Pending,
	FullName:          "Kullanıcı 3",
	Email:             "msk@test.com",
	PhoneNumber:       "05555555555",
	SecondPhoneNumber: "05555555555",
	Description:       "Güzel hizmet",
	DeviceType:        DeviceTypePhone,
	Brand:             BrandApple,
	ModelEntity:       ModelIphone11,
	FixType:           FixType1,
	ServiceType:       ServiceType1,
	ExtraService:      ExtraServiceFirst,
	TechnicalService:  TechnicalService1,
}

var Reservation4 = &tech_service.Reservation{
	ReservationDate:   time.Now(),
	StartOfHour:       12,
	EndOfHour:         13,
	Price:             200,
	Status:            tech_service.Completed,
	FullName:          "Kullanıcı 4",
	Email:             "msk@test.com",
	PhoneNumber:       "05555555555",
	SecondPhoneNumber: "05555555555",
	Description:       "Güzel hizmet",
	DeviceType:        DeviceTypePhone,
	Brand:             BrandApple,
	ModelEntity:       ModelLenovoM7,
	FixType:           FixType1,
	ServiceType:       ServiceType1,
	ExtraService:      ExtraServiceFirst,
	TechnicalService:  TechnicalService1,
}

var Reservation5 = &tech_service.Reservation{
	ReservationDate:   time.Now(),
	StartOfHour:       15,
	EndOfHour:         16,
	Price:             400,
	Status:            tech_service.Approved,
	FullName:          "Kullanıcı 5",
	Email:             "msk@test.com",
	PhoneNumber:       "05555555555",
	SecondPhoneNumber: "05555555555",
	Description:       "Güzel hizmet",
	DeviceType:        DeviceTypePhone,
	Brand:             BrandApple,
	ModelEntity:       ModelLenovoM7,
	FixType:           FixType1,
	ServiceType:       ServiceType1,
	ExtraService:      ExtraServiceFirst,
	TechnicalService:  TechnicalService1,
}

var Reservation6 = &tech_service.Reservation{
	ReservationDate:   time.Now(),
	StartOfHour:       9,
	EndOfHour:         10,
	Price:             1000,
	Status:            tech_service.Approved,
	FullName:          "Kullanıcı 6",
	Email:             "msk@test.com",
	PhoneNumber:       "05555555555",
	SecondPhoneNumber: "05555555555",
	Description:       "Güzel hizmet",
	DeviceType:        DeviceTypePhone,
	Brand:             BrandApple,
	ModelEntity:       ModelLenovoM7,
	FixType:           FixType1,
	ServiceType:       ServiceType1,
	ExtraService:      ExtraServiceFirst,
	TechnicalService:  TechnicalService1,
}
